global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth:8000"]
    metrics_path: /metrics

  - job_name: "assessment-service"
    static_configs:
      - targets: ["assessment:8000"]
    metrics_path: /metrics

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification:8000"]
    metrics_path: /metrics

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
